remote_theme: jekyll/minima

lang: ja
title: ikmnjr-blog
# 以前使ってたリモートテーマ用
# cover: /asset/cover-image.webp

site:
  author:
    name: ikeda
    email: "ikmonjara2rnmt@gmail.com"

# リモートテーマminima特有の設定
minima:
  skin: dark
  date_format: "%Y-%m-%d"
  social_links:
    twitter: ikmnjrd
    github: ikmnjrd
  
header_pages:
  - about.md
  - index.md
  
show_excerpts: true