author:
  name: ikeda
  email: "ikmonjara2rnmt@gmail.com"

lang: ja
title: ikmnjr-blog
description: > # this means to ignore newlines until "show_excerpts:"
  GitHub Pagesでブログやってみようと思い至る。

show_excerpts: false



# リモートテーマminima特有の設定
minima:
  skin: classic
  date_format: "%Y-%m-%d"
  social_links:
    twitter: ikmnjrd
    github: ikmnjrd
  
#header_pages:
# - about.md
  # - index.md
  


# Build settings
remote_theme: jekyll/minima