author:
  name: K.Ikeda

lang: ja
title: ikmnjr-blog
description: > # this means to ignore newlines until "show_excerpts:"
  GitHub Pagesでブログやってみようと思い至る。


# リモートテーマminima特有の設定
show_excerpts: false

minima:
  skin: classic
  date_format: "%Y-%m-%d"
  social_links:
    twitter: ikmnjrd
    github: ikmnjrd
  
header_pages:
  - about.md
  - index.md
  
google_analytics: ${{ secrets.GTAG_SECRET }}

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
