author:
  name: K.Ikeda

lang: ja
title: ikmnjr-blog
description: > # this means to ignore newlines until "show_excerpts:"
  GitHub Pagesでブログやってみようと思い至る。

paginate: 10
paginate_path: "/page/:num/"

# リモートテーマminima特有の設定
show_excerpts: false

minima:
  skin: classic
  date_format: "%Y-%m-%d"
  social_links:
    twitter: ikmnjrd
    github: ikmnjrd

header_pages:
  - about.md
  - index.md

google_analytics: G-W6W9YD5G74

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-paginate
